data:
  hop_length: 512
  n_fft: 2048
  n_mel: 80
  sample_rate: 44100
  train_path: data\train.txt
  val_path: data\val.txt
model:
  filter_channels: 768
  hidden_channels: 192
  kernel_size: 3
  n_heads: 2
  n_layers: 6
  n_speakers: 1
  p_dropout: 0.1
  resblock: '1'
  resblock_dilation_sizes:
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  resblock_kernel_sizes:
  - 3
  - 7
  - 11
  upsample_initial_channel: 512
  upsample_kernel_sizes:
  - 16
  - 16
  - 4
  - 4
  upsample_rates:
  - 8
  - 8
  - 2
  - 2
optimization:
  eps: 1.0e-09
  init_lr_ratio: 1
  lr_decay: 0.999
  optim_d: adamw
  optim_g: adamw
  warmup_epochs: 0
  weight_decay: 0.0
train:
  batch_size: 16
  device: cuda
  epochs: 99
  learning_rate: 0.0002
  num_workers: 4
  save_interval: 10
